### ISSUE TITLE
pass in config to sentry

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-sentry#2]
_From @ianstormtaylor on June 7, 2014 1:21_

Sentry allows for a series of configuration options, would be nice to support at least some of the more important ones.

_Copied from original issue: segmentio/analytics.js-integrations#198_

**Comment by ndhoule** [comment]
_From @amccloud on September 17, 2014 3:22_

This would be a nice thing to enable:
http://raven-js.readthedocs.org/en/latest/tips/index.html#decluttering-sentry

**Comment by ndhoule** [comment]
_From @cgarvis on November 18, 2014 16:49_

It would also be nice to be able to pass in the app version to Sentry: https://www.getsentry.com/docs/tags/

**Comment by ndhoule** [comment]
_From @jivinivan on December 1, 2014 19:14_

:+1: This would also be very useful to us.

**Comment by ndhoule** [comment]
_From @chaselee on December 1, 2014 19:35_

:+1:

**Comment by ndhoule** [comment]
_From @sperand-io on January 20, 2015 21:56_

FYI, +1 from another customer here @ndhoule @amillet89 @harrietgrace :)

https://segment.zendesk.com/agent/tickets/22659

**Comment by simpixelated** [comment]
This issue was closed over a year ago, but I wasn't able to find any clear documentation on whether it's fixed or not. But for anyone else looking to solve the problem, I was able to update `Raven.config` on the fly by calling the Raven specific methods:

```js
window.analytics.ready(() => {
    window.Raven.setRelease(__VERSION__);
});
```

There may be an easier way to do this, but it works for me.

For reference:
- `setRelease` in raven-js code: https://github.com/getsentry/raven-js/blob/66e6f98f41131313cb968e3647af7835689fcf86/src/raven.js#L521
- discussion of setting config values after calling `Raven.install()`: https://github.com/getsentry/raven-js/issues/277
