### ISSUE TITLE
Upgrade to Sentry JavaScript SDK 3.x.x

### ISSUE THREAD

**Issue by pauloschilling** [segment-integrations/analytics.js-integration-sentry#8]
Here: http://blog.getsentry.com/2015/12/29/sentry-js-sdk-release.html

> - Reports now sent via HTTP POST
> - Better automatic wrapping of functions
> - The jQuery, Native, and Backbone plugins have been removed

Also https://github.com/getsentry/raven-js

**Comment by wyattjoh** [comment]
Currently 2.2.0 is the current version, seems that errors are not being reported on our frontend using this integration, not sure if I've done anything wrong?

**Comment by mattrobenolt** [comment]
Hey, from Sentry here. We've had a number of users request this as well, since 1.x is pretty out of date by now and is severely lacking in functionality.

In the meantime, until Segment is updated, I'd recommend anyone just use raven.js directly. See https://docs.getsentry.com/hosted/clients/javascript/ for our docs.

**Comment by f2prateek** [comment]
Hi! This on our (Segment) backlog, but hasn't pending other integration fixes. I don't have a timeline for the upgrade, but happy to accept PRs in the meantime.
